const countries = {
    AE: "United Arab Emirates",
    CC: "Cocos (Keeling) Islands",
    CX: "Christmas Island",
    CY: "Cyprus",
    IO: "British Indian Ocean Territory",
    KP: "Korea, Democratic People's Republic of",
    NF: "Norfolk Island",
    YT: "Mayotte",
    AF: "Afghanistan",
    AM: "Armenia",
    AS: "American Samoa",
    AU: "Australia",
    AZ: "Azerbaijan",
    BD: "Bangladesh",
    BH: "Bahrain",
    BN: "Brunei Darussalam",
    BT: "Bhutan",
    CK: "Cook Islands",
    CN: "China",
    FJ: "Fiji",
    FM: "Micronesia, Federated States of",
    GE: "Georgia",
    GU: "Guam",
    HK: "Hong Kong",
    ID: "Indonesia",
    IL: "Israel",
    IN: "India",
    IQ: "Iraq",
    IR: "Iran, Islamic Republic of",
    JO: "Jordan",
    JP: "Japan",
    KG: "Kyrgyzstan",
    KH: "Cambodia",
    KI: "Kiribati",
    KR: "Korea, Republic of",
    KW: "Kuwait",
    KZ: "Kazakhstan",
    LA: "Lao People's Democratic Republic",
    LB: "Lebanon",
    LK: "Sri Lanka",
    MH: "Marshall Islands",
    MM: "Myanmar",
    MN: "Mongolia",
    MO: "Macao",
    MP: "Northern Mariana Islands",
    MV: "Maldives",
    MY: "Malaysia",
    NC: "New Caledonia",
    NP: "Nepal",
    NR: "Nauru",
    NZ: "New Zealand",
    OM: "Oman",
    PF: "French Polynesia",
    PG: "Papua New Guinea",
    PH: "Philippines",
    PK: "Pakistan",
    PN: "Pitcairn",
    PS: "Palestine, State of",
    PW: "Palau",
    QA: "Qatar",
    SA: "Saudi Arabia",
    SB: "Solomon Islands",
    SG: "Singapore",
    SY: "Syrian Arab Republic",
    TH: "Thailand",
    TJ: "Tajikistan",
    TK: "Tokelau",
    TL: "Timor-Leste",
    TM: "Turkmenistan",
    TO: "Tonga",
    TR: "Turkey",
    TV: "Tuvalu",
    TW: "Taiwan, Province of China",
    UZ: "Uzbekistan",
    VN: "Viet Nam",
    VU: "Vanuatu",
    WF: "Wallis and Futuna",
    WS: "Samoa",
    YE: "Yemen",
    BM: "Bermuda",
    CW: "Curaçao",
    NU: "Niue",
    UM: "United States Minor Outlying Islands",
    GS: "South Georgia and the South Sandwich Islands",
    HM: "Heard Island and McDonald Islands",
    AQ: "Antarctica",
    AG: "Antigua and Barbuda",
    AI: "Anguilla",
    AN: "Netherlands Antilles",
    AR: "Argentina",
    AW: "Aruba",
    BB: "Barbados",
    BL: "Saint Barthélemy",
    BO: "Bolivia",
    BR: "Brazil",
    BS: "Bahamas",
    BZ: "Belize",
    CA: "Canada",
    CL: "Chile",
    CO: "Colombia",
    CR: "Costa Rica",
    CU: "Cuba",
    DM: "Dominica",
    DO: "Dominican Republic",
    EC: "Ecuador",
    GD: "Grenada",
    GF: "French Guiana",
    GL: "Greenland",
    GP: "Guadeloupe",
    GT: "Guatemala",
    GY: "Guyana",
    HN: "Honduras",
    HT: "Haiti",
    JM: "Jamaica",
    KN: "Saint Kitts and Nevis",
    KY: "Cayman Islands",
    LC: "Saint Lucia",
    MF: "Saint Martin (French part)",
    MQ: "Martinique",
    MS: "Montserrat",
    MX: "Mexico",
    NI: "Nicaragua",
    PA: "Panama",
    PE: "Peru",
    PR: "Puerto Rico",
    PY: "Paraguay",
    SR: "Suriname",
    SV: "El Salvador",
    TC: "Turks and Caicos Islands",
    TT: "Trinidad and Tobago",
    US: "United States",
    UY: "Uruguay",
    VC: "Saint Vincent and the Grenadines",
    VE: "Venezuela",
    VG: "British Virgin Islands",
    VI: "United States Virgin Islands",
    AD: "Andorra",
    BQ: "Bonaire, Sint Eustatius and Saba",
    GG: "Guernsey",
    JE: "Jersey",
    SH: "Saint Helena, Ascension and Tristan da Cunha",
    PM: "Saint Pierre and Miquelon",
    RE: "Réunion",
    SX: "Sint Maarten (Dutch part)",
    TF: "French Southern Territories",
    BV: "Bouvet Island",
    FK: "Falkland Islands (Malvinas)",
    AL: "Albania",
    AO: "Angola",
    AT: "Austria",
    AX: "Åland Islands",
    BA: "Bosnia and Herzegovina",
    BE: "Belgium",
    BF: "Burkina Faso",
    BG: "Bulgaria",
    BI: "Burundi",
    BJ: "Benin",
    BW: "Botswana",
    BY: "Belarus",
    CD: "Congo, The Democratic Republic of the",
    CF: "Central African Republic",
    CG: "Congo",
    CH: "Switzerland",
    CI: "Côte d'Ivoire",
    CM: "Cameroon",
    CV: "Cabo Verde",
    CZ: "Czech Republic",
    DE: "Germany",
    DJ: "Djibouti",
    DK: "Denmark",
    DZ: "Algeria",
    EE: "Estonia",
    EG: "Egypt",
    EH: "Western Sahara",
    ER: "Eritrea",
    ES: "Spain",
    ET: "Ethiopia",
    FI: "Finland",
    FO: "Faroe Islands",
    FR: "France",
    GA: "Gabon",
    GB: "United Kingdom",
    GH: "Ghana",
    GI: "Gibraltar",
    GM: "Gambia",
    GN: "Guinea",
    GQ: "Equatorial Guinea",
    GR: "Greece",
    GW: "Guinea-Bissau",
    HR: "Croatia",
    HU: "Hungary",
    IE: "Ireland",
    IM: "Isle of Man",
    IS: "Iceland",
    IT: "Italy",
    KE: "Kenya",
    KM: "Comoros",
    LI: "Liechtenstein",
    LR: "Liberia",
    LS: "Lesotho",
    LT: "Lithuania",
    LU: "Luxembourg",
    LV: "Latvia",
    LY: "Libya",
    MA: "Morocco",
    MC: "Monaco",
    MD: "Moldova",
    ME: "Montenegro",
    MG: "Madagascar",
    MK: "North Macedonia",
    ML: "Mali",
    MR: "Mauritania",
    MT: "Malta",
    MU: "Mauritius",
    MW: "Malawi",
    MZ: "Mozambique",
    NA: "Namibia",
    NE: "Niger",
    NG: "Nigeria",
    NL: "Netherlands",
    NO: "Norway",
    PL: "Poland",
    PT: "Portugal",
    RO: "Romania",
    RS: "Serbia",
    RU: "Russian Federation",
    RW: "Rwanda",
    SC: "Seychelles",
    SD: "Sudan",
    SE: "Sweden",
    SI: "Slovenia",
    SJ: "Svalbard and Jan Mayen",
    SK: "Slovakia",
    SL: "Sierra Leone",
    SM: "San Marino",
    SN: "Senegal",
    SO: "Somalia",
    SS: "South Sudan",
    ST: "Sao Tome and Principe",
    SZ: "Eswatini",
    TD: "Chad",
    TG: "Togo",
    TN: "Tunisia",
    TZ: "Tanzania",
    UA: "Ukraine",
    UG: "Uganda",
    VA: "Holy See (Vatican City State)",
    XK: "Kosovo",
    ZA: "South Africa",
    ZM: "Zambia",
    ZW: "Zimbabwe",
};
export default countries;
